language: node_js
node_js:
  - '10'
  - '11'
  - '12'
os:
  - linux
script:
  - npm run test
  - npm run test:integration
  - cd client && npm ci && npm run test
after_success:
  - npm run build:production
notifications:
  email: false
