language: node_js
node_js:
  - '6'
  - '8'
  - '10'
os:
  - linux
script:
  - npm run test
  - npm run test:integration
  - cd client && npm run test
after_success:
  - npm run build:production
notifications:
  email: false
