name: WPC-Emu CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build WPC-Emu Library
      run: |
        npm ci
        npm run test
        npm run test:integration

    - name: Build WPC-Emu Client
      run: |
        cd client && npm ci && npm run test && cd ..

    - name: Build WPC-Emu Typescript definitions
      run: |
        cd types && npm ci && npm run lint && npm run test && cd ..
        npm run build:production

      env:
        CI: true
